### ISSUE TITLE
Download does not work

### ISSUE THREAD

**Issue by jbarth-ubhd** [cisocrgroup/pocoweb#64]
in docker logs I've found tons of `zip warning: No such file or directory` messages.

Additional messages found:
```
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::directory_iterator::construct: : "/project-data/oobzyltllleiaojy/oobzyltllleiaojy_Montfaucon_montfaucon1719bd2_1_1719/project-d
ata/oobzyltllleiaojy/line-images/0000000060"
zip I/O error: 
zip error: Could not create output file (was replacing the original zip file)
/apps/startup.sh: line 18:    10 Aborted                 (core dumped) /usr/local/bin/pcwd $@
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::remove: Directory not empty: "/project-data/sfbywmafgfwfmuaf/sfbywmafgfwfmuaf__mitmusverb1930_2018/project-data/sfbywmafgfwfmuaf/line-images"
/apps/startup.sh: line 18:     9 Aborted                 (core dumped) /usr/local/bin/pcwd $@

2022/01/20 10:51:22 http: proxy error: EOF
2022/01/20 10:51:22 http: proxy error: dial tcp 172.18.0.5:80: connect: connection refused

2022-01-20 10:51:22 49 [Warning] Aborted connection 49 to db: 'pocoweb' user: 'pocoweb' host: '172.18.0.5' (Got an error reading communication packets)
```

**Comment by jbarth-ubhd** [comment]
ok found .zip files.

Additional found .xml files with actual date, but uncorrected content, but corrected content in .xml in .zip?

**Comment by jbarth-ubhd** [comment]
**(core dumped)**

**Comment by jbarth-ubhd** [comment]
Ok now I have a book with "Download" button working, **but** the path is https://xyz.ub.uni-heidelberg.de/project-data/sfbywmafgfwfmuaf/sfbywmafgfwfmuaf__mitmusverb1930_2018.zip instead of https://xyz.ub.uni-heidelberg.de/pocoweb/project-data/sfbywmafgfwfmuaf/sfbywmafgfwfmuaf__mitmusverb1930_2018.zip .

`Alias`d this in webserver-config, but shouldn't be the path below /pocoweb/ (or similar)?

**Comment by jbarth-ubhd** [comment]
PS: the ocr from thbe download that worked is Abbyy-XML: 
```xml
<document xmlns="http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml" version="1.0" producer="ABBYY FineReader Engine 11" languages="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml">
```

**Comment by finkf** [comment]
The download endpoint returns a relative download location to the archive: 
```json
{
"archive":"project-data/coatxqdtqlfhauar/coatxqdtqlfhauar_Goethe_Die_Wahlverwandtaften_1814.zip"
}
```
From this the download should work IMHO. I will look into this.

**Comment by jbarth-ubhd** [comment]
![image](https://user-images.githubusercontent.com/30653779/153408451-a866dc94-f129-40de-b064-c8bba4afc51c.png)

**Comment by jbarth-ubhd** [comment]
```
80195b10a74b pocoweb_pocoweb ===================================================
(2022-02-10 12:06:05) [INFO    ] Request: 172.18.0.9:45874 0x7f52acb2c070 HTTP/1.1 GET /api-version
(2022-02-10 12:06:05) [INFO    ] /api-version: 0.9.20
(2022-02-10 12:06:05) [INFO    ] (CrtpRoute) Response CODE: 200
(2022-02-10 12:06:05) [INFO    ] Response: 0x7f52acb2c070 /api-version 200 0
(2022-02-10 12:07:22) [INFO    ] Request: 172.18.0.9:45892 0x7f52acb2d600 HTTP/1.1 GET /books
(2022-02-10 12:07:22) [INFO    ] (BookRoute) GET packages for user: 2
(2022-02-10 12:07:22) [INFO    ] (CrtpRoute) Response CODE: 200
(2022-02-10 12:07:22) [INFO    ] Response: 0x7f52acb2d600 /books?auth=XXX&userid=2 200 0
(2022-02-10 12:07:30) [INFO    ] Request: 172.18.0.9:45908 0x7f52acb2eb50 HTTP/1.1 GET /books/6
(2022-02-10 12:07:30) [INFO    ] (BookRoute) GET package: 6
(2022-02-10 12:07:30) [INFO    ] (CrtpRoute) Response CODE: 200
(2022-02-10 12:07:30) [INFO    ] Response: 0x7f52acb2eb50 /books/6?auth=XXX 200 0
(2022-02-10 12:07:30) [INFO    ] Request: 172.18.0.9:45908 0x7f52acb2eb50 HTTP/1.1 GET /books/6/statistics
(2022-02-10 12:07:30) [INFO    ] (StatisticsRoute) GET statistics: 6
(2022-02-10 12:07:30) [INFO    ] Request: 172.18.0.9:45926 0x7f52acb2c0a0 HTTP/1.1 GET /books
(2022-02-10 12:07:30) [INFO    ] (BookRoute) GET packages for user: 2
(2022-02-10 12:07:30) [INFO    ] (CrtpRoute) Response CODE: 200
(2022-02-10 12:07:30) [INFO    ] Response: 0x7f52acb2c0a0 /books?auth=XXX&userid=2 200 0
(2022-02-10 12:07:40) [INFO    ] (CrtpRoute) Response CODE: 200
(2022-02-10 12:07:40) [INFO    ] Response: 0x7f52acb2eb50 /books/6/statistics?auth=XXX 200 0
(2022-02-10 12:07:45) [INFO    ] Request: 172.18.0.9:45942 0x7f52acb2d610 HTTP/1.1 GET /books/6/download
(2022-02-10 12:07:46) [ERROR   ] exception: basic_string::insert: __pos (which is 33) > this->size() (which is 20)
(2022-02-10 12:07:46) [INFO    ] Response: 0x7f52acb2d610 /books/6/download?auth=XXX 500 0
```

**Comment by finkf** [comment]
I finally could reproduce your error. Commit 0091ae4e should fix it

**Comment by jbarth-ubhd** [comment]
Hmm... still the same problem:
```
(2022-02-18 12:22:36) [ERROR   ] exception: basic_string::insert: __pos (which i
s 33) > this->size() (which is 20)

...

2022-02-18 12:17:11 0 [ERROR] Incorrect definition of table mysql.event: expecte
d column 'definer' at position 3 to have type varchar(, found type char(141).   
2022-02-18 12:17:11 0 [ERROR] mariadbd: Event Scheduler: An error occurred when 
initializing system tables. Disabling the Event Scheduler. 
```

**Comment by novacellus** [comment]
The same error seems to affect the hOCR export functionality:
```
Request: xxx.xx.x.x:xxxxx 0x7f781e72c080 HTTP/1.1 GET /books/31/download
Assertion failed: pos < chars_.size() (rest/src/parser/HocrParserLine.cpp: insert: 120)
```

**Comment by jbarth-ubhd** [comment]
We've done a lot of work in pocoweb and want to export it. @finkf , could you clairfy this?

**Comment by jbarth-ubhd** [comment]
Dear @finkf, 
I've updated everything (apparently it updated submodules only) on 2022-09-30.
Still the same problem — we can't download our projects, still the same error.

Could you please look for this?
